### ISSUE TITLE
Am I running this incorrectly?

### ISSUE THREAD

**Issue by tc185187** [seancook/docker-openpose-cpu#4]
So I pulled and built the image and when I run using the "Usage" section of the README I'm getting this as output and the image I put in data has no inference overlaid / no other image was created with the pose keypoints. Basically, I am unsure if anything is even happening. Plz help :)  
<img width="629" alt="Screen Shot 2022-04-08 at 10 34 33 AM" src="https://user-images.githubusercontent.com/87485318/162458100-85eaf334-b81c-446a-a9c7-6e83dc0dc171.png">

**Comment by tc185187** [comment]
Nvm I big dumb stupid idiot. Just needed to increase docker mem :) as already addressed in readme

**Comment by seancook** [comment]
Great, glad you saw that. I was just about to ask :)
